// flow-typed signature: 61800a00ba319e3d8fe6f2cd36fe9785
// flow-typed version: <<STUB>>/cxs_v^6.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cxs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cxs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cxs/benchmarks/index' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/cxs' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/emotion' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/fela' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/glamorous' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/inline-styles' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/styled-components' {
  declare module.exports: any;
}

declare module 'cxs/component' {
  declare module.exports: any;
}

declare module 'cxs/dist/Box' {
  declare module.exports: any;
}

declare module 'cxs/dist/component' {
  declare module.exports: any;
}

declare module 'cxs/dist/createTheme' {
  declare module.exports: any;
}

declare module 'cxs/dist/index' {
  declare module.exports: any;
}

declare module 'cxs/dist/ThemeProvider' {
  declare module.exports: any;
}

declare module 'cxs/ThemeProvider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cxs/benchmarks/index.js' {
  declare module.exports: $Exports<'cxs/benchmarks/index'>;
}
declare module 'cxs/benchmarks/lib/cxs.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/cxs'>;
}
declare module 'cxs/benchmarks/lib/emotion.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/emotion'>;
}
declare module 'cxs/benchmarks/lib/fela.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/fela'>;
}
declare module 'cxs/benchmarks/lib/glamorous.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/glamorous'>;
}
declare module 'cxs/benchmarks/lib/inline-styles.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/inline-styles'>;
}
declare module 'cxs/benchmarks/lib/styled-components.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/styled-components'>;
}
declare module 'cxs/component.js' {
  declare module.exports: $Exports<'cxs/component'>;
}
declare module 'cxs/dist/Box.js' {
  declare module.exports: $Exports<'cxs/dist/Box'>;
}
declare module 'cxs/dist/component.js' {
  declare module.exports: $Exports<'cxs/dist/component'>;
}
declare module 'cxs/dist/createTheme.js' {
  declare module.exports: $Exports<'cxs/dist/createTheme'>;
}
declare module 'cxs/dist/index.js' {
  declare module.exports: $Exports<'cxs/dist/index'>;
}
declare module 'cxs/dist/ThemeProvider.js' {
  declare module.exports: $Exports<'cxs/dist/ThemeProvider'>;
}
declare module 'cxs/ThemeProvider.js' {
  declare module.exports: $Exports<'cxs/ThemeProvider'>;
}
