// flow-typed signature: 45db658b9c4be15527072591d9d87246
// flow-typed version: <<STUB>>/dist-size_v^0.3.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dist-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dist-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dist-size/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dist-size/cli.js' {
  declare module.exports: $Exports<'dist-size/cli'>;
}
declare module 'dist-size/index' {
  declare module.exports: $Exports<'dist-size'>;
}
declare module 'dist-size/index.js' {
  declare module.exports: $Exports<'dist-size'>;
}
