// flow-typed signature: 9a4c85c33a3abd90bda8d2ccb34423d1
// flow-typed version: <<STUB>>/helmet_v^3.8.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'helmet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'helmet/index' {
  declare module.exports: $Exports<'helmet'>;
}
declare module 'helmet/index.js' {
  declare module.exports: $Exports<'helmet'>;
}
