// flow-typed signature: 7395a285b49328f6819f651998aee64e
// flow-typed version: <<STUB>>/logdown_v^3.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'logdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'logdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'logdown/dist/logdown' {
  declare module.exports: any;
}

declare module 'logdown/dist/logdown.min' {
  declare module.exports: any;
}

declare module 'logdown/src/base' {
  declare module.exports: any;
}

declare module 'logdown/src/browser' {
  declare module.exports: any;
}

declare module 'logdown/src/markdown/browser' {
  declare module.exports: any;
}

declare module 'logdown/src/markdown/get-next-match' {
  declare module.exports: any;
}

declare module 'logdown/src/markdown/node' {
  declare module.exports: any;
}

declare module 'logdown/src/markdown/rules/browser' {
  declare module.exports: any;
}

declare module 'logdown/src/markdown/rules/node' {
  declare module.exports: any;
}

declare module 'logdown/src/node' {
  declare module.exports: any;
}

declare module 'logdown/src/util/get-global' {
  declare module.exports: any;
}

declare module 'logdown/src/util/is-color-supported/browser' {
  declare module.exports: any;
}

declare module 'logdown/src/util/is-color-supported/node' {
  declare module.exports: any;
}

declare module 'logdown/src/util/is-firefox' {
  declare module.exports: any;
}

declare module 'logdown/src/util/is-webkit' {
  declare module.exports: any;
}

declare module 'logdown/src/util/to-array' {
  declare module.exports: any;
}

// Filename aliases
declare module 'logdown/dist/logdown.js' {
  declare module.exports: $Exports<'logdown/dist/logdown'>;
}
declare module 'logdown/dist/logdown.min.js' {
  declare module.exports: $Exports<'logdown/dist/logdown.min'>;
}
declare module 'logdown/src/base.js' {
  declare module.exports: $Exports<'logdown/src/base'>;
}
declare module 'logdown/src/browser.js' {
  declare module.exports: $Exports<'logdown/src/browser'>;
}
declare module 'logdown/src/markdown/browser.js' {
  declare module.exports: $Exports<'logdown/src/markdown/browser'>;
}
declare module 'logdown/src/markdown/get-next-match.js' {
  declare module.exports: $Exports<'logdown/src/markdown/get-next-match'>;
}
declare module 'logdown/src/markdown/node.js' {
  declare module.exports: $Exports<'logdown/src/markdown/node'>;
}
declare module 'logdown/src/markdown/rules/browser.js' {
  declare module.exports: $Exports<'logdown/src/markdown/rules/browser'>;
}
declare module 'logdown/src/markdown/rules/node.js' {
  declare module.exports: $Exports<'logdown/src/markdown/rules/node'>;
}
declare module 'logdown/src/node.js' {
  declare module.exports: $Exports<'logdown/src/node'>;
}
declare module 'logdown/src/util/get-global.js' {
  declare module.exports: $Exports<'logdown/src/util/get-global'>;
}
declare module 'logdown/src/util/is-color-supported/browser.js' {
  declare module.exports: $Exports<'logdown/src/util/is-color-supported/browser'>;
}
declare module 'logdown/src/util/is-color-supported/node.js' {
  declare module.exports: $Exports<'logdown/src/util/is-color-supported/node'>;
}
declare module 'logdown/src/util/is-firefox.js' {
  declare module.exports: $Exports<'logdown/src/util/is-firefox'>;
}
declare module 'logdown/src/util/is-webkit.js' {
  declare module.exports: $Exports<'logdown/src/util/is-webkit'>;
}
declare module 'logdown/src/util/to-array.js' {
  declare module.exports: $Exports<'logdown/src/util/to-array'>;
}
