// flow-typed signature: 493c8dd5072e5738b4bf5e45bcd71686
// flow-typed version: <<STUB>>/react-materialize_v^1.0.11/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-materialize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-materialize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-materialize/lib/Autocomplete' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Badge' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Button' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Card' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CardPanel' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CardTitle' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Carousel' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Chip' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Col' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Collapsible' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CollapsibleItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Collection' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CollectionItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/constants' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Container' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Divider' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Dropdown' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Footer' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Icon' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/idgen' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Input' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/MediaBox' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/MenuItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Modal' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Navbar' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/NavItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Overlay' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Pagination' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/PaginationButton' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Parallax' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Preloader' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Row' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/SearchForm' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Section' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/SideNav' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/SideNavItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Slide' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Slider' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Spinner' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tab' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Table' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tabs' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tag' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Toast' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/UserView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-materialize/lib/Autocomplete.js' {
  declare module.exports: $Exports<'react-materialize/lib/Autocomplete'>;
}
declare module 'react-materialize/lib/Badge.js' {
  declare module.exports: $Exports<'react-materialize/lib/Badge'>;
}
declare module 'react-materialize/lib/Breadcrumb.js' {
  declare module.exports: $Exports<'react-materialize/lib/Breadcrumb'>;
}
declare module 'react-materialize/lib/Button.js' {
  declare module.exports: $Exports<'react-materialize/lib/Button'>;
}
declare module 'react-materialize/lib/Card.js' {
  declare module.exports: $Exports<'react-materialize/lib/Card'>;
}
declare module 'react-materialize/lib/CardPanel.js' {
  declare module.exports: $Exports<'react-materialize/lib/CardPanel'>;
}
declare module 'react-materialize/lib/CardTitle.js' {
  declare module.exports: $Exports<'react-materialize/lib/CardTitle'>;
}
declare module 'react-materialize/lib/Carousel.js' {
  declare module.exports: $Exports<'react-materialize/lib/Carousel'>;
}
declare module 'react-materialize/lib/Chip.js' {
  declare module.exports: $Exports<'react-materialize/lib/Chip'>;
}
declare module 'react-materialize/lib/Col.js' {
  declare module.exports: $Exports<'react-materialize/lib/Col'>;
}
declare module 'react-materialize/lib/Collapsible.js' {
  declare module.exports: $Exports<'react-materialize/lib/Collapsible'>;
}
declare module 'react-materialize/lib/CollapsibleItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/CollapsibleItem'>;
}
declare module 'react-materialize/lib/Collection.js' {
  declare module.exports: $Exports<'react-materialize/lib/Collection'>;
}
declare module 'react-materialize/lib/CollectionItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/CollectionItem'>;
}
declare module 'react-materialize/lib/constants.js' {
  declare module.exports: $Exports<'react-materialize/lib/constants'>;
}
declare module 'react-materialize/lib/Container.js' {
  declare module.exports: $Exports<'react-materialize/lib/Container'>;
}
declare module 'react-materialize/lib/Divider.js' {
  declare module.exports: $Exports<'react-materialize/lib/Divider'>;
}
declare module 'react-materialize/lib/Dropdown.js' {
  declare module.exports: $Exports<'react-materialize/lib/Dropdown'>;
}
declare module 'react-materialize/lib/Footer.js' {
  declare module.exports: $Exports<'react-materialize/lib/Footer'>;
}
declare module 'react-materialize/lib/Icon.js' {
  declare module.exports: $Exports<'react-materialize/lib/Icon'>;
}
declare module 'react-materialize/lib/idgen.js' {
  declare module.exports: $Exports<'react-materialize/lib/idgen'>;
}
declare module 'react-materialize/lib/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/index'>;
}
declare module 'react-materialize/lib/Input.js' {
  declare module.exports: $Exports<'react-materialize/lib/Input'>;
}
declare module 'react-materialize/lib/MediaBox.js' {
  declare module.exports: $Exports<'react-materialize/lib/MediaBox'>;
}
declare module 'react-materialize/lib/MenuItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/MenuItem'>;
}
declare module 'react-materialize/lib/Modal.js' {
  declare module.exports: $Exports<'react-materialize/lib/Modal'>;
}
declare module 'react-materialize/lib/Navbar.js' {
  declare module.exports: $Exports<'react-materialize/lib/Navbar'>;
}
declare module 'react-materialize/lib/NavItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/NavItem'>;
}
declare module 'react-materialize/lib/Overlay.js' {
  declare module.exports: $Exports<'react-materialize/lib/Overlay'>;
}
declare module 'react-materialize/lib/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-materialize/lib/OverlayTrigger'>;
}
declare module 'react-materialize/lib/Pagination.js' {
  declare module.exports: $Exports<'react-materialize/lib/Pagination'>;
}
declare module 'react-materialize/lib/PaginationButton.js' {
  declare module.exports: $Exports<'react-materialize/lib/PaginationButton'>;
}
declare module 'react-materialize/lib/Parallax.js' {
  declare module.exports: $Exports<'react-materialize/lib/Parallax'>;
}
declare module 'react-materialize/lib/Preloader.js' {
  declare module.exports: $Exports<'react-materialize/lib/Preloader'>;
}
declare module 'react-materialize/lib/ProgressBar.js' {
  declare module.exports: $Exports<'react-materialize/lib/ProgressBar'>;
}
declare module 'react-materialize/lib/Row.js' {
  declare module.exports: $Exports<'react-materialize/lib/Row'>;
}
declare module 'react-materialize/lib/SearchForm.js' {
  declare module.exports: $Exports<'react-materialize/lib/SearchForm'>;
}
declare module 'react-materialize/lib/Section.js' {
  declare module.exports: $Exports<'react-materialize/lib/Section'>;
}
declare module 'react-materialize/lib/SideNav.js' {
  declare module.exports: $Exports<'react-materialize/lib/SideNav'>;
}
declare module 'react-materialize/lib/SideNavItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/SideNavItem'>;
}
declare module 'react-materialize/lib/Slide.js' {
  declare module.exports: $Exports<'react-materialize/lib/Slide'>;
}
declare module 'react-materialize/lib/Slider.js' {
  declare module.exports: $Exports<'react-materialize/lib/Slider'>;
}
declare module 'react-materialize/lib/Spinner.js' {
  declare module.exports: $Exports<'react-materialize/lib/Spinner'>;
}
declare module 'react-materialize/lib/Tab.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tab'>;
}
declare module 'react-materialize/lib/Table.js' {
  declare module.exports: $Exports<'react-materialize/lib/Table'>;
}
declare module 'react-materialize/lib/Tabs.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tabs'>;
}
declare module 'react-materialize/lib/Tag.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tag'>;
}
declare module 'react-materialize/lib/Toast.js' {
  declare module.exports: $Exports<'react-materialize/lib/Toast'>;
}
declare module 'react-materialize/lib/UserView.js' {
  declare module.exports: $Exports<'react-materialize/lib/UserView'>;
}
