// flow-typed signature: a619345258f07f82fa8c3df19e2a8a9c
// flow-typed version: <<STUB>>/webpack-messages_v^1.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-messages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-messages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-messages/index' {
  declare module.exports: $Exports<'webpack-messages'>;
}
declare module 'webpack-messages/index.js' {
  declare module.exports: $Exports<'webpack-messages'>;
}
