// flow-typed signature: d1374493efd2898cce4706960aefc0f6
// flow-typed version: <<STUB>>/webpack-chain_v^4.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-chain'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-chain' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-chain/src/Chainable' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/ChainedMap' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/ChainedSet' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/Config' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/DevServer' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/Module' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/Output' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/Performance' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/Plugin' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/Resolve' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/ResolveLoader' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/Rule' {
  declare module.exports: any;
}

declare module 'webpack-chain/src/Use' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-chain/src/Chainable.js' {
  declare module.exports: $Exports<'webpack-chain/src/Chainable'>;
}
declare module 'webpack-chain/src/ChainedMap.js' {
  declare module.exports: $Exports<'webpack-chain/src/ChainedMap'>;
}
declare module 'webpack-chain/src/ChainedSet.js' {
  declare module.exports: $Exports<'webpack-chain/src/ChainedSet'>;
}
declare module 'webpack-chain/src/Config.js' {
  declare module.exports: $Exports<'webpack-chain/src/Config'>;
}
declare module 'webpack-chain/src/DevServer.js' {
  declare module.exports: $Exports<'webpack-chain/src/DevServer'>;
}
declare module 'webpack-chain/src/Module.js' {
  declare module.exports: $Exports<'webpack-chain/src/Module'>;
}
declare module 'webpack-chain/src/Output.js' {
  declare module.exports: $Exports<'webpack-chain/src/Output'>;
}
declare module 'webpack-chain/src/Performance.js' {
  declare module.exports: $Exports<'webpack-chain/src/Performance'>;
}
declare module 'webpack-chain/src/Plugin.js' {
  declare module.exports: $Exports<'webpack-chain/src/Plugin'>;
}
declare module 'webpack-chain/src/Resolve.js' {
  declare module.exports: $Exports<'webpack-chain/src/Resolve'>;
}
declare module 'webpack-chain/src/ResolveLoader.js' {
  declare module.exports: $Exports<'webpack-chain/src/ResolveLoader'>;
}
declare module 'webpack-chain/src/Rule.js' {
  declare module.exports: $Exports<'webpack-chain/src/Rule'>;
}
declare module 'webpack-chain/src/Use.js' {
  declare module.exports: $Exports<'webpack-chain/src/Use'>;
}
