// flow-typed signature: 982f87ace32eecf18b3c298f69f28a55
// flow-typed version: <<STUB>>/@hocs/debounce-handler_v^0.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/debounce-handler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/debounce-handler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/debounce-handler/dist/debounce-handler' {
  declare module.exports: any;
}

declare module '@hocs/debounce-handler/dist/debounce-handler.min' {
  declare module.exports: any;
}

declare module '@hocs/debounce-handler/es/index' {
  declare module.exports: any;
}

declare module '@hocs/debounce-handler/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/debounce-handler/dist/debounce-handler.js' {
  declare module.exports: $Exports<'@hocs/debounce-handler/dist/debounce-handler'>;
}
declare module '@hocs/debounce-handler/dist/debounce-handler.min.js' {
  declare module.exports: $Exports<'@hocs/debounce-handler/dist/debounce-handler.min'>;
}
declare module '@hocs/debounce-handler/es/index.js' {
  declare module.exports: $Exports<'@hocs/debounce-handler/es/index'>;
}
declare module '@hocs/debounce-handler/lib/index.js' {
  declare module.exports: $Exports<'@hocs/debounce-handler/lib/index'>;
}
