// flow-typed signature: a3ba1f8b72a6c9513cfbdcfaa1b0683d
// flow-typed version: <<STUB>>/@hocs/omit-props_v^0.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/omit-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/omit-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/omit-props/dist/omit-props' {
  declare module.exports: any;
}

declare module '@hocs/omit-props/dist/omit-props.min' {
  declare module.exports: any;
}

declare module '@hocs/omit-props/es/index' {
  declare module.exports: any;
}

declare module '@hocs/omit-props/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/omit-props/dist/omit-props.js' {
  declare module.exports: $Exports<'@hocs/omit-props/dist/omit-props'>;
}
declare module '@hocs/omit-props/dist/omit-props.min.js' {
  declare module.exports: $Exports<'@hocs/omit-props/dist/omit-props.min'>;
}
declare module '@hocs/omit-props/es/index.js' {
  declare module.exports: $Exports<'@hocs/omit-props/es/index'>;
}
declare module '@hocs/omit-props/lib/index.js' {
  declare module.exports: $Exports<'@hocs/omit-props/lib/index'>;
}
