// flow-typed signature: b10786f8d65b555df964450837cc6cac
// flow-typed version: <<STUB>>/@hocs/prevent-handlers-default_v^0.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/prevent-handlers-default'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/prevent-handlers-default' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/prevent-handlers-default/dist/prevent-handlers-default' {
  declare module.exports: any;
}

declare module '@hocs/prevent-handlers-default/dist/prevent-handlers-default.min' {
  declare module.exports: any;
}

declare module '@hocs/prevent-handlers-default/es/index' {
  declare module.exports: any;
}

declare module '@hocs/prevent-handlers-default/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/prevent-handlers-default/dist/prevent-handlers-default.js' {
  declare module.exports: $Exports<'@hocs/prevent-handlers-default/dist/prevent-handlers-default'>;
}
declare module '@hocs/prevent-handlers-default/dist/prevent-handlers-default.min.js' {
  declare module.exports: $Exports<'@hocs/prevent-handlers-default/dist/prevent-handlers-default.min'>;
}
declare module '@hocs/prevent-handlers-default/es/index.js' {
  declare module.exports: $Exports<'@hocs/prevent-handlers-default/es/index'>;
}
declare module '@hocs/prevent-handlers-default/lib/index.js' {
  declare module.exports: $Exports<'@hocs/prevent-handlers-default/lib/index'>;
}
