// flow-typed signature: b3af5eab86304bcf1507f6bd346bae96
// flow-typed version: <<STUB>>/@hocs/safe-timers_v^0.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/safe-timers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/safe-timers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/safe-timers/dist/safe-timers' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/dist/safe-timers.min' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/es/index' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/es/safeTimerFactory' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/es/withSafeAnimationFrame' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/es/withSafeIdleCallback' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/es/withSafeInterval' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/es/withSafeTimeout' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/lib/index' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/lib/safeTimerFactory' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/lib/withSafeAnimationFrame' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/lib/withSafeIdleCallback' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/lib/withSafeInterval' {
  declare module.exports: any;
}

declare module '@hocs/safe-timers/lib/withSafeTimeout' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/safe-timers/dist/safe-timers.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/dist/safe-timers'>;
}
declare module '@hocs/safe-timers/dist/safe-timers.min.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/dist/safe-timers.min'>;
}
declare module '@hocs/safe-timers/es/index.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/es/index'>;
}
declare module '@hocs/safe-timers/es/safeTimerFactory.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/es/safeTimerFactory'>;
}
declare module '@hocs/safe-timers/es/withSafeAnimationFrame.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/es/withSafeAnimationFrame'>;
}
declare module '@hocs/safe-timers/es/withSafeIdleCallback.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/es/withSafeIdleCallback'>;
}
declare module '@hocs/safe-timers/es/withSafeInterval.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/es/withSafeInterval'>;
}
declare module '@hocs/safe-timers/es/withSafeTimeout.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/es/withSafeTimeout'>;
}
declare module '@hocs/safe-timers/lib/index.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/lib/index'>;
}
declare module '@hocs/safe-timers/lib/safeTimerFactory.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/lib/safeTimerFactory'>;
}
declare module '@hocs/safe-timers/lib/withSafeAnimationFrame.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/lib/withSafeAnimationFrame'>;
}
declare module '@hocs/safe-timers/lib/withSafeIdleCallback.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/lib/withSafeIdleCallback'>;
}
declare module '@hocs/safe-timers/lib/withSafeInterval.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/lib/withSafeInterval'>;
}
declare module '@hocs/safe-timers/lib/withSafeTimeout.js' {
  declare module.exports: $Exports<'@hocs/safe-timers/lib/withSafeTimeout'>;
}
