// flow-typed signature: 66f8be6435ad1df2e23476b75b28d948
// flow-typed version: <<STUB>>/@hocs/with-match-media-props_v^0.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/with-match-media-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/with-match-media-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/with-match-media-props/dist/with-match-media-props' {
  declare module.exports: any;
}

declare module '@hocs/with-match-media-props/dist/with-match-media-props.min' {
  declare module.exports: any;
}

declare module '@hocs/with-match-media-props/es/index' {
  declare module.exports: any;
}

declare module '@hocs/with-match-media-props/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/with-match-media-props/dist/with-match-media-props.js' {
  declare module.exports: $Exports<'@hocs/with-match-media-props/dist/with-match-media-props'>;
}
declare module '@hocs/with-match-media-props/dist/with-match-media-props.min.js' {
  declare module.exports: $Exports<'@hocs/with-match-media-props/dist/with-match-media-props.min'>;
}
declare module '@hocs/with-match-media-props/es/index.js' {
  declare module.exports: $Exports<'@hocs/with-match-media-props/es/index'>;
}
declare module '@hocs/with-match-media-props/lib/index.js' {
  declare module.exports: $Exports<'@hocs/with-match-media-props/lib/index'>;
}
