// flow-typed signature: 2e67c4b219e619d210ea858b90e587f8
// flow-typed version: <<STUB>>/@hocs/with-callback-once_v^0.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/with-callback-once'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/with-callback-once' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/with-callback-once/dist/with-callback-once' {
  declare module.exports: any;
}

declare module '@hocs/with-callback-once/dist/with-callback-once.min' {
  declare module.exports: any;
}

declare module '@hocs/with-callback-once/es/index' {
  declare module.exports: any;
}

declare module '@hocs/with-callback-once/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/with-callback-once/dist/with-callback-once.js' {
  declare module.exports: $Exports<'@hocs/with-callback-once/dist/with-callback-once'>;
}
declare module '@hocs/with-callback-once/dist/with-callback-once.min.js' {
  declare module.exports: $Exports<'@hocs/with-callback-once/dist/with-callback-once.min'>;
}
declare module '@hocs/with-callback-once/es/index.js' {
  declare module.exports: $Exports<'@hocs/with-callback-once/es/index'>;
}
declare module '@hocs/with-callback-once/lib/index.js' {
  declare module.exports: $Exports<'@hocs/with-callback-once/lib/index'>;
}
