// flow-typed signature: 827b44c909ca886ded637c3d882964da
// flow-typed version: <<STUB>>/@hocs/with-log_v^0.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/with-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/with-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/with-log/dist/with-log' {
  declare module.exports: any;
}

declare module '@hocs/with-log/dist/with-log.min' {
  declare module.exports: any;
}

declare module '@hocs/with-log/es/index' {
  declare module.exports: any;
}

declare module '@hocs/with-log/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/with-log/dist/with-log.js' {
  declare module.exports: $Exports<'@hocs/with-log/dist/with-log'>;
}
declare module '@hocs/with-log/dist/with-log.min.js' {
  declare module.exports: $Exports<'@hocs/with-log/dist/with-log.min'>;
}
declare module '@hocs/with-log/es/index.js' {
  declare module.exports: $Exports<'@hocs/with-log/es/index'>;
}
declare module '@hocs/with-log/lib/index.js' {
  declare module.exports: $Exports<'@hocs/with-log/lib/index'>;
}
