// flow-typed signature: 15035dabd2fdb55c786956ad9670e958
// flow-typed version: <<STUB>>/@hocs/with-lifecycle_v^0.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/with-lifecycle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/with-lifecycle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/with-lifecycle/dist/with-lifecycle' {
  declare module.exports: any;
}

declare module '@hocs/with-lifecycle/dist/with-lifecycle.min' {
  declare module.exports: any;
}

declare module '@hocs/with-lifecycle/es/index' {
  declare module.exports: any;
}

declare module '@hocs/with-lifecycle/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/with-lifecycle/dist/with-lifecycle.js' {
  declare module.exports: $Exports<'@hocs/with-lifecycle/dist/with-lifecycle'>;
}
declare module '@hocs/with-lifecycle/dist/with-lifecycle.min.js' {
  declare module.exports: $Exports<'@hocs/with-lifecycle/dist/with-lifecycle.min'>;
}
declare module '@hocs/with-lifecycle/es/index.js' {
  declare module.exports: $Exports<'@hocs/with-lifecycle/es/index'>;
}
declare module '@hocs/with-lifecycle/lib/index.js' {
  declare module.exports: $Exports<'@hocs/with-lifecycle/lib/index'>;
}
