// flow-typed signature: 2a6fbe914b5f152939546325ce5545d7
// flow-typed version: <<STUB>>/@hocs/with-debugger_v^0.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/with-debugger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/with-debugger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/with-debugger/dist/with-debugger' {
  declare module.exports: any;
}

declare module '@hocs/with-debugger/dist/with-debugger.min' {
  declare module.exports: any;
}

declare module '@hocs/with-debugger/es/index' {
  declare module.exports: any;
}

declare module '@hocs/with-debugger/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/with-debugger/dist/with-debugger.js' {
  declare module.exports: $Exports<'@hocs/with-debugger/dist/with-debugger'>;
}
declare module '@hocs/with-debugger/dist/with-debugger.min.js' {
  declare module.exports: $Exports<'@hocs/with-debugger/dist/with-debugger.min'>;
}
declare module '@hocs/with-debugger/es/index.js' {
  declare module.exports: $Exports<'@hocs/with-debugger/es/index'>;
}
declare module '@hocs/with-debugger/lib/index.js' {
  declare module.exports: $Exports<'@hocs/with-debugger/lib/index'>;
}
