// flow-typed signature: 753c3886dedb759251c18bf2b398881d
// flow-typed version: <<STUB>>/@hocs/with-intersection-observer-props_v^0.3.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/with-intersection-observer-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/with-intersection-observer-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/with-intersection-observer-props/dist/with-intersection-observer-props' {
  declare module.exports: any;
}

declare module '@hocs/with-intersection-observer-props/dist/with-intersection-observer-props.min' {
  declare module.exports: any;
}

declare module '@hocs/with-intersection-observer-props/es/index' {
  declare module.exports: any;
}

declare module '@hocs/with-intersection-observer-props/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/with-intersection-observer-props/dist/with-intersection-observer-props.js' {
  declare module.exports: $Exports<'@hocs/with-intersection-observer-props/dist/with-intersection-observer-props'>;
}
declare module '@hocs/with-intersection-observer-props/dist/with-intersection-observer-props.min.js' {
  declare module.exports: $Exports<'@hocs/with-intersection-observer-props/dist/with-intersection-observer-props.min'>;
}
declare module '@hocs/with-intersection-observer-props/es/index.js' {
  declare module.exports: $Exports<'@hocs/with-intersection-observer-props/es/index'>;
}
declare module '@hocs/with-intersection-observer-props/lib/index.js' {
  declare module.exports: $Exports<'@hocs/with-intersection-observer-props/lib/index'>;
}
