// flow-typed signature: 6bdbc5789afc6712d896137a68d83c69
// flow-typed version: <<STUB>>/@hocs/with-callback-on-change_v^0.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/with-callback-on-change'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/with-callback-on-change' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/with-callback-on-change/dist/with-callback-on-change' {
  declare module.exports: any;
}

declare module '@hocs/with-callback-on-change/dist/with-callback-on-change.min' {
  declare module.exports: any;
}

declare module '@hocs/with-callback-on-change/es/index' {
  declare module.exports: any;
}

declare module '@hocs/with-callback-on-change/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/with-callback-on-change/dist/with-callback-on-change.js' {
  declare module.exports: $Exports<'@hocs/with-callback-on-change/dist/with-callback-on-change'>;
}
declare module '@hocs/with-callback-on-change/dist/with-callback-on-change.min.js' {
  declare module.exports: $Exports<'@hocs/with-callback-on-change/dist/with-callback-on-change.min'>;
}
declare module '@hocs/with-callback-on-change/es/index.js' {
  declare module.exports: $Exports<'@hocs/with-callback-on-change/es/index'>;
}
declare module '@hocs/with-callback-on-change/lib/index.js' {
  declare module.exports: $Exports<'@hocs/with-callback-on-change/lib/index'>;
}
