// flow-typed signature: 5b47f9ac23e25cddb791630e1efbeb64
// flow-typed version: <<STUB>>/@hocs/with-callback-on-change-while_v^0.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hocs/with-callback-on-change-while'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hocs/with-callback-on-change-while' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hocs/with-callback-on-change-while/dist/with-callback-on-change-while' {
  declare module.exports: any;
}

declare module '@hocs/with-callback-on-change-while/dist/with-callback-on-change-while.min' {
  declare module.exports: any;
}

declare module '@hocs/with-callback-on-change-while/es/index' {
  declare module.exports: any;
}

declare module '@hocs/with-callback-on-change-while/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hocs/with-callback-on-change-while/dist/with-callback-on-change-while.js' {
  declare module.exports: $Exports<'@hocs/with-callback-on-change-while/dist/with-callback-on-change-while'>;
}
declare module '@hocs/with-callback-on-change-while/dist/with-callback-on-change-while.min.js' {
  declare module.exports: $Exports<'@hocs/with-callback-on-change-while/dist/with-callback-on-change-while.min'>;
}
declare module '@hocs/with-callback-on-change-while/es/index.js' {
  declare module.exports: $Exports<'@hocs/with-callback-on-change-while/es/index'>;
}
declare module '@hocs/with-callback-on-change-while/lib/index.js' {
  declare module.exports: $Exports<'@hocs/with-callback-on-change-while/lib/index'>;
}
